# Use C-a for prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Synchonized panes
bind s set-window-option synchronize-panes

# Reload config
bind r source-file ~/.tmux.conf

# Hide status bar
bind b set status

# Correct term
set -g default-terminal "screen-256color"

# shorter esc timeout
set escape-time 10

# prettier
#set -g status-style 'bg=#333333 fg=#5eacd3'

# vi copy mode
setw -g mode-keys vi

# larger buffer
set-option -g history-limit 10000
